baseURL = 'https://adaro.eu'
languageCode = 'en-us'
title = 'Antonio de Haro'
copyright = 'Â© Antonio de Haro'

pygmentsUseClasses = true

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]']]
          inline = [['\(', '\)']]

[params]
math = true

[[params.social]]
name = 'GitHub'
icon = 'github'
url = 'https://github.com/dc138'

[[params.social]]
name = 'Linkedin'
icon = 'linkedin'
url = 'https://www.linkedin.com/in/adaromar'
