baseURL = 'https://adaro.eu'
languageCode = 'en-us'
title = 'Antonio de Haro'
copyright = 'Â© Antonio de Haro'

pygmentsstyle = 'monokai'
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
mathjax = true
katex = false

[[params.social]]
name = 'GitHub'
icon = 'github'
url = 'https://github.com/dc138'

[[menu.main]]
name = 'Home'
url = '/'
weight = 1

[[menu.main]]
name = 'Posts'
url = '/posts'
weight = 2

[[menu.main]]
name = 'About'
url = '/about'
weight = 3
